import React, { useEffect, useMemo, useState } from 'react'
import { apiClient, ArtifactEntry } from '../api/client'
import { Card } from './ui'
import toast from 'react-hot-toast'
import { FiRefreshCw } from 'react-icons/fi'

export const ArtifactsViewer: React.FC<{ runId?: string }> = ({ runId }) => {
  const [artifacts, setArtifacts] = useState<ArtifactEntry[]>([])
  const [categories, setCategories] = useState<string[]>([])
  const [categoryFilter, setCategoryFilter] = useState<string>('all')
  const [selected, setSelected] = useState<ArtifactEntry | null>(null)
  const [content, setContent] = useState<string>('')
  const [loading, setLoading] = useState(false)

  const loadArtifacts = async () => {
    setLoading(true)
    try {
      const data = await apiClient.getArtifacts()

      // determine which runs were generated by the user (persisted in localStorage)
      let generatedRuns: string[] = []
      try {
        const raw = localStorage.getItem('generated_runs') || '[]'
        generatedRuns = JSON.parse(raw)
      } catch (err) {
        generatedRuns = []
      }

      // ensure we include the runId if the viewer was called with a runId prop
      const allowedRuns = runId ? Array.from(new Set([...(generatedRuns || []), runId])) : generatedRuns || []

      const filtered = Array.isArray(data)
        ? data.filter((d) => allowedRuns.includes(d.run_id))
        : []

      setArtifacts(filtered)
      const uniqCats = Array.from(new Set(filtered.map((d) => d.category)))
      setCategories(uniqCats)

      // auto-select first artifact if none selected
      if (filtered.length > 0 && !selected) {
        const first = filtered[0]
        setSelected(first)
        try {
          const resp = await apiClient.getArtifactContent(first.run_id, first.file_path)
          setContent(resp?.content || '')
        } catch (err: any) {
          console.warn('failed to load first artifact content', err)
        }
      }
    } catch (err: any) {
      toast.error('Failed to load artifacts')
      console.error(err)
    } finally {
      setLoading(false)
    }
  }

  const loadContent = async (entry: ArtifactEntry) => {
    setSelected(entry)
    setContent('Loading...')
    try {
      const resp = await apiClient.getArtifactContent(entry.run_id, entry.file_path)
      setContent(resp?.content || '')
    } catch (err: any) {
      toast.error('Failed to load artifact content')
      setContent('Failed to load content')
    }
  }

  useEffect(() => {
    loadArtifacts()

    const onRefresh = (_e?: Event) => {
      loadArtifacts()
    }
    window.addEventListener('artifact:refresh', onRefresh as EventListener)

    return () => {
      window.removeEventListener('artifact:refresh', onRefresh as EventListener)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [runId])

  const filtered = useMemo(() => {
    return artifacts.filter((a) => {
      if (categoryFilter !== 'all' && a.category !== categoryFilter) return false
      return true
    })
  }, [artifacts, categoryFilter])

  return (
    <div className="flex gap-6">
      <div className="flex-shrink-0 w-80">
        <Card>
          <div className="flex items-center justify-between mb-3">
            <h3 className="font-semibold">Generated Artifacts</h3>
            <button onClick={loadArtifacts} className="text-sm text-blue-400 hover:text-blue-300">
              <FiRefreshCw />
            </button>
          </div>

          <div className="space-y-3 mb-4">
            <div>
              <label className="text-xs text-muted">Category</label>
              <select
                className="w-full mt-1 px-2 py-1 border rounded-md input-base"
                value={categoryFilter}
                onChange={(e) => setCategoryFilter(e.target.value)}
              >
                <option value="all">All Categories</option>
                {categories.map((c) => (
                  <option key={c} value={c}>
                    {c}
                  </option>
                ))}
              </select>
            </div>
          </div>

          <div className="space-y-2 max-h-[74vh] overflow-auto pr-1">
            {filtered.map((a) => (
              <button
                key={`${a.run_id}-${a.file_path}`}
                onClick={() => loadContent(a)}
                className={`w-full text-left px-3 py-2 rounded-md border transition-colors text-sm ${
                  selected?.file_path === a.file_path && selected?.run_id === a.run_id
                    ? 'bg-white text-black border-transparent'
                    : 'bg-transparent border-transparent hover:bg-white/3'
                }`}
              >
                <div className="text-xs text-muted">{a.category}</div>
                <div className="font-medium truncate">{a.file_name}</div>
                <div className="text-xs text-muted truncate">{a.run_id}</div>
              </button>
            ))}
            {filtered.length === 0 && <div className="text-sm text-muted">No generated artifacts found.</div>}
          </div>
        </Card>
      </div>

      <div className="flex-1 min-w-0">
        <Card>
          <div className="flex items-start justify-between mb-4 pb-4 border-b">
            <div>
              <h2 className="text-xl font-semibold">{selected?.file_name || 'Select an artifact'}</h2>
              <p className="text-sm text-muted">{selected?.file_path}</p>
            </div>
            <div className="text-xs text-muted">
              {selected?.updated_at ? new Date(selected.updated_at).toLocaleString() : ''}
            </div>
          </div>
          <pre className="text-sm surface border border-var rounded-lg p-4 overflow-auto max-h-[70vh] font-mono text-green-200 bg-[#071018]">
            {content || 'Select an artifact to preview.'}
          </pre>
        </Card>
      </div>
    </div>
  )
}

export default ArtifactsViewer
